CONFIG_FLASH_RENESAS_RA_HP_BANK_SWAP=y # Compiles in flash_ra_banks_swap  and flash_ra_ex_op
CONFIG_FLASH_EX_OP_ENABLED=y # relies on flash_ra_ex_op being enabled, sets it as enabled

CONFIG_BOOT_IMAGE_JUMP_HOOKS=y # Jump hooks allows  bank_swap_hook.c to execute code in jump hook
CONFIG_REBOOT=y # allows software rebooting

CONFIG_FLASH_RENESAS_RA_QSPI=n # disable qspi as it has bugs with ex_op