CONFIG_MCUBOOT_GENERATE_CONFIRMED_IMAGE=y # Make the confirmed file for initial flashing

CONFIG_FLASH=y # include the flash drivers
CONFIG_FLASH_MAP=y # include the named partitions so runtime code can access them
CONFIG_STREAM_FLASH=y # 
CONFIG_IMG_MANAGER=y # Zephyrs tool for writing firmware into a slot

CONFIG_FLASH_RENESAS_RA_HP_BANK_SWAP=y # Includes flash_ex_op and bank swap
CONFIG_FLASH_EX_OP_ENABLED=y # enabled version of flash_ex_op


CONFIG_MCUMGR=y # include mcumgr
CONFIG_MCUMGR_GRP_IMG=y # allows the image list and image upload commands
CONFIG_MCUMGR_GRP_OS=y # allows the reset and echo commands from pc terminal
CONFIG_MCUMGR_TRANSPORT_SHELL=y # Mcumgr needs to communicate over shell serial port
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=2475 # size of mcumgt transfer buffer

CONFIG_BASE64=y # text encoding for shell
CONFIG_CRC=y # error checking for shell

CONFIG_NET_BUF=y # packet buffers for mcumgr
CONFIG_ZCBOR=y # message encoding for mcumgr

CONFIG_GPIO=y # gpio pins support
CONFIG_REBOOT=y # allows software rebooting
CONFIG_SHELL=y # allows the shell command line 
CONFIG_SHELL_BACKEND_SERIAL=y # allows the sheell cmd line to be over uart
CONFIG_SHELL_LOG_BACKEND=n # no logs wanted

CONFIG_MAIN_STACK_SIZE=2048 # main thread stack size

CONFIG_FLASH_RENESAS_RA_QSPI=n # there is a bug which stops compiling if qspi is enabled, qspi uses ex_op