SB_CONFIG_BOOTLOADER_MCUBOOT=y # Includes mcuboot

SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP=y # Sets mcuboot to use direct xip

SB_CONFIG_MCUBOOT_DIRECT_XIP_GENERATE_VARIANT=n # stops sysbuild from making a slot 1 variant, wrong address

SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y # optional, more compact encryption